project:
  type: website
  output-dir: docs
  resources:
    - "index.html"
    - "index.css"
    - "style.css"
    - "script.js"
    - "sources/"
    - "courses/**/sources/"

execute:
  freeze: auto

website: 
  title: "Programming Concepts Course"
  page-footer: 
    center: "© 2025 Vadym Katsel. All rights reserved."
  site-url: "https://vadymkatsel.github.io/programming-concepts"
  repo-url: "https://github.com/vadymkatsel/programming-concepts"

  navbar:
      logo: sources/logo.svg
      right:
        - href: courses/math-course/modules/index.qmd
          text: "Математика"
        - href: courses/be-course/modules/index.qmd
          text: "Бізнес Економіка"
  
  sidebar:
    - id: math-sidebar
      title: "Зміст курсу"
      search: true 
      collapse-level: 1
      contents:
        - section: "Вступ та підготовка до курсу"
          contents:
            - courses/math-course/modules/index.qmd 
        
        - section: "Змінні, типи даних. Математичні операції в Python"
          contents:
            - courses/math-course/modules/variables-data-types-operations-practice.qmd
        
        - section: "Списки"
          contents:
            - courses/math-course/modules/lists-practice.qmd

        - section: "Функції"
          contents:
            - courses/math-course/modules/functions-practice.qmd 

        - section: "Основи Git"
          contents:
            - courses/math-course/modules/git-practice.qmd

        - section: "Словники. List Comprehension"
          contents:
            - courses/math-course/modules/dictionaries-lc-practice.qmd
      active-modes: [courses/math-course]

    - id: be-sidebar
      search: true 
      collapse-level: 1
      contents:
        - section: "Вступ та підготовка до курсу"
          contents:
            - courses/be-course/modules/index.qmd 
  
        - section: "Змінні, типи даних. Математичні операції в Python"
          contents: 
            - courses/be-course/modules/variables-data-types-operations-practice.qmd
            
        - section: "Логічні розгалудження"
          contents: 
            - courses/be-course/modules/conditionals-practice.qmd
            - courses/be-course/modules/ATM-simulator-task.qmd

        - section: "Списки та словники"
          contents: 
            - courses/be-course/modules/lists-practice.qmd
            - courses/be-course/modules/dictionaries-tuples-sets-practice.qmd
            - courses/be-course/modules/comprehensions-practice.qmd

        - section: "Рядки"
          contents:
            - courses/be-course/modules/strings-practice.qmd

        - section: "Функції"
          contents: 
            - courses/be-course/modules/functions-practice.qmd

        - section: "Робота з файлами"
          contents: 
            - courses/be-course/modules/files-practice.qmd

        - section: "Бібліотеки, JSON"
          contents: 
            - courses/be-course/modules/libraries-json-practice.qmd

      active-modes: [courses/be-course]

format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    mainfont: 'Lilex'
    css: style.css
    number-sections: false
    favicon: images/favicon.svg
    include-in-header:
      text: |
        <link rel="icon" type="image/svg+xml" href="https://vadymkatsel.github.io/programming-concepts/images/favicon.svg">
    include-after-body:
      text: |
        <script src="/script.js"></script>


