project:
  type: website
  output-dir: docs
  resources:
    - "index.html"
    - "index.css"
    - "style.css"
    - "script.js"
    - "sources/"
    - "courses/**/sources/"

execute:
  freeze: auto

website: 
  title: "Programming Concepts Course"
  page-footer: 
    center: "© 2025 Vadym Katsel. All rights reserved."
  site-url: "https://vadymkatsel.github.io/programming-concepts"
  repo-url: "https://github.com/vadymkatsel/programming-concepts"

  navbar:
      logo: sources/logo.svg
      right:
        - href: courses/math-course/modules/index.qmd
          text: "Математика"
        - href: courses/be-course/modules/index.qmd
          text: "Бізнес Економіка"
  
  sidebar:
    - id: math-sidebar
      title: "Математика в IT"
      search: true 
      collapse-level: 1
      contents:
        - section: "Вступ та підготовка до курсу"
          contents:
            - courses/math-course/modules/index.qmd 
        
        - section: "Змінні, типи даних. Математичні операції в Python"
          contents:
            - courses/math-course/modules/variables-data-types-operations-practice.qmd
        
        - section: "Списки"
          contents:
            - courses/math-course/modules/lists-practice.qmd

        - section: "Функції"
          contents:
            # - modules/functions-practice.qmd # Розкоментуй, як допишеш

        - section: "Основи Git"
          contents:
            - courses/math-course/modules/git-practice.qmd

        - section: "Словники. List Comprehension"
          contents:
            # - modules/dicts-practice.qmd
      active-modes: [courses/math-course]

    - id: be-sidebar
      search: true 
      collapse-level: 1
      contents:
        - section: "Вступ та підготовка до курсу"
          contents:
            - courses/be-course/modules/index.qmd 
      active-modes: [courses/be-course]

format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    mainfont: 'Lilex'
    css: style.css
    number-sections: false
    favicon: images/favicon.svg
    include-in-header:
      text: |
        <link rel="icon" type="image/svg+xml" href="https://vadymkatsel.github.io/programming-concepts/images/favicon.svg">
    include-after-body:
      text: |
        <script src="/script.js"></script>


