---
title: "Змінні, типи даних та операції"
toc: true
lang: ua
execute:
  eval: false
page-layout: full
---

## 📌 Завдання 1

Уявіть, що вам необхідно написати простий калькулятор вартості замовлення для ресторану. Необхідно, щоб у користувача була можливість ввести назву страви, її ціну, кількість замовлених порцій та знижку у відсотках. Також необхідно врахувати, що на вартість обіду впливає податок на додану вартість (ПДВ), який становить 20%.

Приклад виконання програми:

``` markdown
Enter the name of the dish: Borshch
Enter the price of the dish: 100
Enter the quantity of portions: 2
Enter the discount (%): 10

The total of <quantity> <name> will be <total> UAH, including <tax> UAH tax.
```

## 🔍 Поради щодо виконання

1. Використовуйте функцію `input()` для отримання даних від користувача.
2. Перетворюйте введені дані у відповідні типи (наприклад, `float` для ціни та знижки, `int` для кількості).
3. Використовуйте змінні для збереження введених даних та проміжних обчислень.
4. Для виведення результату використовуйте функцію `print()` та f-рядки (форматовані рядки).

::: {.callout-tip}
Для цього завдання ми не перевірятимемо коректність введення користувача та приймемо як належне, що користувач вводить лише коректні дані.
:::
