---
title: "👋🏻 Hello, World!"
toc: true
lang: ua
execute:
  eval: false
page-layout: full
---

## 📚 Про курс

Цей ресурс було створено з метою полегшення доступу до навчальних матеріалів. Він є основною базою знань, де будуть зібрані більшість практичних занять та деякі навчальні матеріал.

На цьому курсі ми охопимо всі знання, які необхідні для базового програмування на Pyhon. Ми пройдемо шлях від розуміння того, як працюють базові типи даних, до основ об'єктно-орієнтованого програмування та роботи з реальними файлами.

### 📂 Що всередині?

Курс розбитий на логічні модулі:

* **Основи Python:** змінні, математичні операції, списки та функції.
* **Структури даних:** занурення у словники та list comprehension.
* **Робота з даними:** читання та запис файлів, обробка помилок.
* **Контроль версій:** базові навички роботи з Git для збереження вашого прогресу.
* **Робота з біліотеками та  API:** знайомство з бібліотеками `pandas`, `matplotlib`  та іншими 

### 🏗️ Архітектура навчання

Кожна тема курсу побудована за ітеративним підходом, що дозволяє максимально ефективно трансформувати теорію у практичні навички:

1. **Cheat Sheets:** На початку кожної теми на вас чекає концентрована вижимка ключових концепцій та синтаксису.
2. **Теоретичний мінімум:** Якщо темі не передувала окрема лекція, ми надаємо необхідну базу для глибинного розуміння матеріалу.
3. **Live Coding:** Практична демонстрація застосування концепцій у реальному часі. Ми разом розбираємо, як код працює "під капотом".
4. **Guided Practice:** Виконання базових завдань самостійно для закріплення механіки та патернів написання коду. У вас є можливість експериментувати, ставити запитання під час виконання, а в кінці шанс отримати рев'ю.

## 💻 Як користуватися цим сайтом

Сайт створений так, щоб вам було максимально зручно фокусуватися на коді:

1. **Навігація:** Використовуйте бічне меню ліворуч для переходу між темами.
2. **Пошук:** Якщо забули якусь концепцію і хочете швидко її знайти, використовуйте іконку пошуку у верхньому правому куті.
3. **Сніпети коду:** Усі приклади коду можна легко скопіювати в один клік за допомогою іконки копіювання, яка з'являється при наведенні на блок з кодом.
4. **Тема:** У верхньому меню можна перемикати світлу та темну теми екрана для комфортного читання.

## 🚀 Готові почати?

Тож не гаймо часу та переходьмо до першого розділу, щоб підготувати своє робоче середовище.

[Почати: Встановлення середовища](ide-variables-operations/ide-setup-ps.qmd){.btn .btn-primary}