---
title: "Practice Session 13"
toc: true
lang: ua
execute:
  eval: false
page-layout: full
format:
  html:
    include-in-header: 
    - text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
---

## Основи роботи з JSON та CSV файлами

В реальному світі інформація рідко зберігається суцільним текстом - зазвичай вона має чітку структуру. Сьогодні ми розберемо два найпопулярніші формати зберігання та обміну даних: **CSV** (який ви часто зустрінете при роботі з таблицями та датасетами) та **JSON** (головний стандарт для передачі даних у вебі та роботи з API). Вміння читати, парсити та зберігати дані у цих форматах - це необхідна база для створення повноцінних програм.

:::callout-note
# Зауважте!
Для успішного виконання цієї практичної, вам знадобиться зробити Fork [репозиторію](https://github.com/vkatsel/files-practice.git), а потім клонувати його на свій пристрій. Для того, аби здати практичну, вам потрібно буде надіслати pull request
:::

## 📌 План заняття: 
- 📊 JSON та CSV - стандарт для роботи з даними
- 👨‍💻 Live coding 1: Клітинки, коми та значення
- 👨‍💻 Live Coding 2: JSON
- 👨‍💻 Live Coding 3: Залишити свій слід в JSON

## 📊 JSON та CSV - стандарт для роботи з даними

При обробці великих даних за допомогою роботи з файлами ми зазвичай виділяємо два найпоширеніші формати - `.json` та `.csv`. Ці формати використовуються для різних сценаріїв передачі та зберігання даних

-  `.csv`
- `.json`

Як і при роботі з будь яким файлом, наш сценарій залишається не змінним:

1. Відкрити файл
2. Зчитати та опрацювати дані
3. Закрити файл (якщо є така потреба)

Нижче ви можете побачити чіт шіт для роботи з цими розширеннями файлів.

### 📝 Cheat Sheet

#### Робота з JSON (import json)
JSON ідеально підходить для збереження списків та словників. Метод load() автоматично перетворює текст на об'єкти Python, а dump() — навпаки.

##### Читання:

```{python}
import json
with open("data.json", "r", encoding="utf-8") as f:
    # Отримуємо готовий список або словник
    data = json.load(f) 
```

##### Запис:
```{python}
import json
my_data = [{"name": "John", "age": 30}]

with open("export.json", "w", encoding="utf-8") as f:
    # indent=4 робить файл читабельним (з відступами)
    json.dump(my_data, f, indent=4) 

```

#### Робота з CSV

##### Читання:
```{python}
import csv
with open("table.csv", "r", encoding="utf-8") as f:
    reader = csv.reader(f)
    next(reader) # Пропускаємо перший рядок (заголовки)
    for row in reader:
        print(row[0]) # Звертаємося до колонок за індексом
```

##### Запис:
- **Спосіб 1:** Звичайний 
Використовуємо, коли наші дані — це списки: ["Apple", 15].

```{python}
import csv
data = [["Name", "Price"], ["Apple", 15], ["Banana", 20]]

with open("output.csv", "w", encoding="utf-8", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data) # Записує список списків
    # writer.writerow(["Тільки", "один", "рядок"]) 
```

- **Спосіб 2:** DictWriter
Найкращий спосіб, якщо ми отримали дані у вигляді списку словників (наприклад, розпарсили JSON).

```{python}
import csv
data = [{"name": "Apple", "price": 15}, {"name": "Banana", "price": 20}]
columns = ["name", "price"] # Задаємо ключі

with open("output_dict.csv", "w", encoding="utf-8", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=columns)
    writer.writeheader()   # Автоматично пише рядок із заголовками
    writer.writerows(data) # Пише всі словники
```

:::callout-important
# Важливо
При записі у CSV завжди додавайте `newline=""` у функцію `open()`, щоб уникнути порожніх рядків на Windows.
:::

### 👨‍💻 Live coding 1: Клітинки, коми та значення

**Контекст:** В контексті цього завдання нам з вами доведеться стати справжніми аналітиками та проаналізувати дані про товари, що збергіються на складі магазину "Very Cool Store". У нас є датасет формату `.csv`, розміром в 1000 рядків, в якому зберігаються різні дані. Нас цікавить, зокрема ціна та кількість товарів (Price and Stock). Наша задача - порахувати загальну суму вартості товарів, які зберігаються на складі. Поле `"Availability"` таких товарів - `in_stock`

**Вхідні дані:** 
```{python}
#| eval: true
#| echo: false
#| classes: info-table

import pandas as pd

df = pd.read_csv("../sources/products-1000.csv")

(df.head(10).style
    .hide(axis="index")
    .set_caption("Датасет products-1000.csv") 
    .set_table_styles([

        {'selector': 'th', 'props': 'background-color: rgba(128, 128, 128, 0.15); color: #333; font-weight: bold; text-align: left; padding: 10px; border-bottom: 2px solid rgba(128, 128, 128, 0.3);'},

        # {'selector': 'tr:hover', 'props': 'background-color: #5fafff;'},

        {'selector': 'td', 'props': 'padding: 10px; border-bottom: 1px solid rgba(128, 128, 128, 0.15); text-align: left;'}
    ])
)
```


**Очікуваний результат:** Загальна сума товарів, які зберігаються на складі

#### 🛠 Guided Practice:

**Контекст:** Після загального аналізу повної вартості всіх товарів, вам також потрібно дізнатися середню ціну одного товару в нашому асортименті, а також знайти, який товар є найдорожчим. До обробки, як і раніше, тільки ті товари, які ми маємо `in_stock`

**Вхідні дані:** Датасет `products-1000.csv`

**Очікуваний результат:** Вивід середньої вартості одного товару, найдорожчий товар та його вартість.

:::callout-tip
# Порада щодо виконання

При обробці великої кількості даних, важливо вміти визначати конкретні кроки для знаходження потрібних результатів. Для цієї задачі можете скористатися наступним порядком дій:

- Порахувати середнє значення ціни товару
- Додати пошук найдорожчого товару
:::

### 👨‍💻 Live Coding 2: JSON 

**Контекст:**  Ми працюємо з даними про клієнтів компанії. Ці дані зберігаються віддалено у форматі JSON. Нам (не інакше як чудом) вдалося витягнути ці дані на свій комп'ютер, і тепер перед нами постала задача, отримана від маркетологів: ми маємо з'ясувати чи виправдано запускати рекламну кампанію в штаті Каліфорнія. Для цього маємо дізнатися, скільки користувачів ми маємо в цьому штаті.

**Вхідні дані:** Датасет формату JSON. Частина структури подана нижче

```{json}
[
   {
      "id":1,
      "name":"Emily Johnson",
      "company":"ABC Corporation",
      "username":"emily_johnson",
      "email":"emily.johnson@abccorporation.com",
      "address":"123 Main St",
      "zip":"12345",
      "state":"California",
      "country":"USA",
      "phone":"+1-555-123-4567",
      "photo":"https://loremflickr.com/1076/2263?lock&#x3D;1311373814763876"
   },
   {
      "id":2,
      "name":"Michael Williams",
      "company":"XYZ Corp",
      "username":"michael_williams",
      "email":"michael.williams@xyzcorp.com",
      "address":"456 Elm Ave",
      "zip":"67890",
      "state":"New York",
      "country":"USA",
      "phone":"+1-555-987-6543"
   }
]
```

**Очікуваний результат:** Загальна кількість користувачів, та кількість користувачів з Каліфорнії

#### 🛠 Guided Practice:

**Контекст:** Поки ми шукали кількість користувачів з каліфорнії, маркетологи згенерували нову геніальну ідею: запустити email-розсилку. Аби розуміти аудиторію краще, їм потрібно дізнатися, який відсоток користувачів використовує комерційні поштові скриньки (ті, що закінчуються на `.com`)

Використовуючи той самий файл `data.json`, вам потрібно порахувати загальну кількість людей і знайти тих, у кого значення по ключу `email` закінчується на `.com`. Після цього вирахувати відсоток таких користувачів від загальної кількості.

**Вхідні дані:** Файл `data.json`

**Очікуваний результат:** Відсоток людей, що використовують комерційні поштові скриньки

:::callout-tip
# Підказка
Ви можете скористатися методом `.endswith("")` аби перевірити яке саме закінчення має рядок
:::

### 👨‍💻 Live Coding 3: Залишити свій слід в JSON

**Контекст:** Усіх наших зусиль, витрачених на обробку файлів виявилось недостатньо: тепер від нас вимагають записати всіх людей, які проживають у Каліфронії в окремий файл. Для цього, нам потрібно створити новий файл, який потім можна буде нарешті передати до відділу маркетингу

**Вхідні дані:** файл `data.json` з Live Coding 2

**Очікуваний результат:** Новий файл `californians.json`
